#!/usr/bin/env python3

import argparse
from collections import defaultdict
import csv
import lxml.etree as ET
import sys

#NS = {'alto': 'http://www.loc.gov/standards/alto/ns-v3#'}
#ET.register_namespace('alto', 'http://www.loc.gov/standards/alto/ns-v3#')

parser = argparse.ArgumentParser(description='Read Google Renewals')
parser.add_argument('-f', '--file', metavar='XML', type=argparse.FileType('r'),
                    help='XML file to process')
parser.add_argument('-y', '--year', metavar='YEAR', help='Year to filter')
args = parser.parse_args()


tree = ET.parse(args.file)
root = tree.getroot()

fieldnames = set()
recs = []
for record in root.findall('./Record'):
    if 'web-%s' % args.year in record.find('File').text:

        fields = [f.split(':\t') for f in record.find('Snippet').text.split('\n') if f != '']

        d = defaultdict(list)
        for k, v in fields:
#            print(type(v))
            d[k].append(v)

        dd = dict([(b[0],'|'.join(b[1])) for b in d.items()])
        recs += [dd]
        fieldnames = fieldnames.union(dd.keys())

writer = csv.DictWriter(sys.stdout, fieldnames=fieldnames, delimiter='\t')
writer.writeheader()
for r in recs:
    writer.writerow(r)
