#!/usr/bin/env python3 -u

import argparse
import csv
import os
import re

def parsed_file(d, f):
    try:
        lines = 0
        parsed = 0
        with open(os.path.join(d,f)) as p:
            reader = csv.DictReader(p, delimiter='\t')
            for row in reader:
                lines += 1
                parsed += 1 if row['oreg'] else 0
        return {'lines out': lines, 'lines parsed': parsed}
    except IndexError:
        return {'lines': 0, 'lines parsed': 0}


def get_stats(d, f):
    return {**{'year': f[0:4]},
            **parsed_file(d, f)}


def to_pct(i, o):
    if o == 0 or i == 0:
        return 'n/a'

    return '{:5.2f}'.format(((o*1.0)/(i*1.0))*100)


def format_row(r):
    print('{:>5s} {:>5s} {:>5} {:>6s}'.format(
        r['year'],
        str(r['lines out']) if r['lines out'] else 'n/a',
        str(r['lines parsed']) if r['lines parsed'] else 'n/a',
        to_pct(r['lines out'], r['lines parsed']))) 

def get_files(d):
    return [f for f in os.listdir(d) if re.match(r'\d{4}\-parsed', f)]


parser = argparse.ArgumentParser(description='Report stats on renewal files')
parser.add_argument('-d', '--data-dir', metavar='DIR', type=str,
                    help='Data directory to examine')
args = parser.parse_args()

for f in get_files(args.data_dir):
    format_row(get_stats(args.data_dir, f))
